### ISSUE TITLE
Pulling together some thoughts for Purpose chapter draft

### ISSUE THREAD

**Issue by bclarke-nes** [nhs-r-community/statements-on-tools#22]
I wanted to start bringing some thoughts together about the overarching purpose chapter. Roughly:

- I'll move some of the material from section 3.1 (about tools) into the main purposes chapter. It'll do more work there as part of a general introduction to the handbook, and allow us to cut to the chase on the specific tools/packages issues
- I'll copy some of the points over from 2.1 too
- And make some general comments about R / use in the NHS, based on @wbryant 's discussion in [#4](https://github.com/nhs-r-community/statements-on-tools/issues/4#issue-1230143779)  

Question: what else should I look at for this? Any suggestions very welcome.

**Comment by wbryant** [comment]
Sorry for the delay, this looks like a sensible set of steps - have started on a fork for this?  Happy to give feedback at any point.

**Comment by wbryant** [comment]
One point I think we should make a conscious decision on is in the more general sections (e.g. "purpose") we shouldn't be specific about R unless the section is specific to R.  We support open code in R and Python and also potentially other languages and using other tools, so being agnostic where we can is probably more inclusive.
