### ISSUE TITLE
GitHub Action failing - missing image

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/statements-on-tools#31]
```
Error in knitr::include_graphics("images/logo.jpg", dpi = NA) : 
```
Possibly better to link to https://github.com/nhs-r-community/assets/tree/main/logo?

**Comment by Lextuga007** [comment]
Might also be that the merge conflict code is still in the scripts: https://github.com/nhs-r-community/statements-on-tools/blob/d0b16b0a4f50d32993be74f2dddd850a5c6961ee/index.Rmd

**Comment by tomjemmett** [comment]
better off linking to the hosted version: https://nhs-r-community.github.io/assets/logo/nhsr-logo.svg
