### ISSUE TITLE
Integrate the content from this book with NHS-R Way

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/statements-on-tools#50]
There are a few cross overs on the content with NHS-R Way and also there is now a difference in book type between the two as NHS-R Way is Quarto (it was released many months after this was created). 

In order to keep this open to R and Python users should this book be moved to quarto or merged directly into the NHS-R Way?

**Comment by ChrisBeeley** [comment]
So is this repo deprecated now then?

**Comment by Lextuga007** [comment]
No. I'm reluctant to deprecate this as it's been contributed to by a lot of people and it sits separately to the [NHS-R Way](https://nhs-r-community.github.io/NHSR-way/) as these are guides, tools and suggestions. I think, for now, it's best to link this to the NHS-R Way.

**Comment by Lextuga007** [comment]
I've now made this a Quarto book and I can see the benefit of merging them altogether - search being one of them! I'll see if there is a way to merge repositories to retain others' input.
